### ISSUE TITLE
mt6735 5.1 audio not playing yet

### ISSUE THREAD

**Issue by olegsvs** [Creeplays/MTK-Pin-Finder#4]
Running test for Audio
Found pre exec function, running...
Got answer from preExec function: Acheron.ogg, running command... // not playing
Executed, waiting for timeout...
Pins for Audio is 137,142 // lie
Maybe this trouble with ogg files

java.lang.NullPointerException: storage == null
    at android.os.Parcel.readException(Parcel.java:1552)
    at android.os.Parcel.readException(Parcel.java:1499)
    at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2495)
    at com.android.commands.am.Am.runStart(Am.java:766)
    at com.android.commands.am.Am.onRun(Am.java:305)
    at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
    at com.android.commands.am.Am.main(Am.java:97)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

this example alais not work am start -a android.intent.action.VIEW -d 'file:///system/media/audio/notifications/Adara.ogg' -t 'audio/ogg' 

maybe use this universal method https://gist.github.com/olegsvs/c30e37b48f353e9d520b263589b34fcc

**Comment by CertainLach** [comment]
Can you precompile it?
